trigger:
- master

pr:
- '*'

variables:
- group: AzureKeyVault
- name: BuildNumber
  value: $[counter('buildnumber')]

jobs:
- job: Windows
  pool:
    vmImage: windows-2019
  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core 3.0
    inputs:
      version: '3.0.x'
      packageType: sdk
  - task: UseDotNet@2
    displayName: Install .NET Core 2.2
    inputs:
      version: '2.2.x'
      packageType: runtime
  - powershell: ./build.ps1 -ci
    displayName: Invoke build.ps1
    env:
      KEYVAULT_CLIENT_SECRET: $(kv-access-token)
  - task: PublishTestResults@2
    displayName: Upload test results
    condition: always()
    continueOnError: true
    inputs:
      testRunTitle: Windows
      testRunner: vstest
      testResultsFiles: '**/*.trx'
  - publish: 'artifacts/'
    artifact: 'Packages'
    displayName: Publish artifacts
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core 3.0
    inputs:
      version: '3.0.x'
      packageType: sdk
  - task: UseDotNet@2
    displayName: Install .NET Core 2.2
    inputs:
      version: '2.2.x'
      packageType: runtime
  - script: ./build.ps1 -ci
    displayName: Invoke build.ps1
  - task: PublishTestResults@2
    displayName: Upload test results
    condition: always()
    continueOnError: true
    inputs:
      testRunTitle: Linux
      testRunner: vstest
      testResultsFiles: '**/*.trx'
